default_language_version:
  python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-yaml
      - id: check-case-conflict
      - id: detect-private-key
      - id: requirements-txt-fixer
      - id: end-of-file-fixer
      - id: trailing-whitespace

  # Jupyter notebook specific hooks
  - repo: https://github.com/nbQA-dev/nbQA
    rev: 1.7.0
    hooks:
    - id: nbqa-black  # PEP 8 compliant opinionated formatter
      additional_dependencies: [black==22.3.0]
    - id: nbqa-pyupgrade  # Upgrade syntax to newer versions
      additional_dependencies: [pyupgrade==2.7.3]
    - id: nbqa-isort  # Sort imports in Jupiter Notebooks
      additional_dependencies: [isort==5.6.4]

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: Format imports

  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 23.10.1
    hooks:
      - id: black-jupyter
        name: Format code
        additional_dependencies: ['click==8.0.2']

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: 'v0.1.4'
    hooks:
      - id: ruff  # (Linter) Check for common mistakes in Python code
